version: "3.8"

services:
  emqx:
    image: emqx/emqx:6.0
    container_name: emqx
    ports:
      - "1883:1883" # MQTT port
      - "8083:8083" # WebSocket port
      - "8084:8084" # WSS port
      - "8883:8883" # MQTT SSL port
      - "18083:18083" # Dashboard port
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
      - EMQX_NODE__COOKIE=emqxsecretcookie
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  simulator:
    build:
      context: .
      dockerfile: iot_simulator/Dockerfile
    container_name: oee-simulator
    depends_on:
      emqx:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

volumes:
  emqx-data:
  emqx-log:
