version: "3.8"

name: oee-factory-monitor

services:
  emqx:
    image: emqx/emqx:6.0
    container_name: emqx
    ports:
      #- "1883:1883" # MQTT port
      #- "8083:8083" # WebSocket port
      #- "8084:8084" # WSS port
      #- "8883:8883" # MQTT SSL port
      - "18083:18083" # Dashboard port
    env_file:
      - .env
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  simulator:
    build:
      context: .
      dockerfile: iot_simulator/Dockerfile
    container_name: oee-simulator
    depends_on:
      emqx:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestor:
    build:
      context: .
      dockerfile: ingestion_service/Dockerfile
    container_name: oee-ingestor
    depends_on:
      emqx:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

volumes:
  emqx-data:
  emqx-log:
  timescaledb-data:
